export const SALES_HISTORY_CONSTANTS = {
  STRING_ZERO: '0',
  DATE: {
    DEFAULT_START_TIME: '00:00:00',
    DEFAULT_END_TIME: '23:59:59',
    DATE_SEPARATOR: '-',
    TIME_SEPARATOR: ':',
    DATE_TIME_SEPARATOR: 'T',
    MONTH_PADDING: 2,
    DAY_PADDING: 2
  }
};
