services:
  frontend:
    image: ${CONTATODO_WEB_IMAGE:?CONTATODO_WEB_IMAGE is required}
    container_name: contatodo-web
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=${BACKEND_URL:?BACKEND_URL is required}
    networks:
      - contatodo-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  contatodo-network:
    external: true
